myapp/board/urls.py
from django.urls import path
from .views import base_views, answer_views, question_views, comment_views, vote_views

# 네임스페이스 지정
app_name = "board"

urlpatterns = [
    path("", base_views.index, name="index"),
    # 질문 생성
    path("<int:question_id>", base_views.detail, name="detail"),
    # /board/question/create/ question_create
    path("question/create/", question_views.question_create, name="question_create"),
    # /board/question/modify/305
    path(
        "question/modify/<int:question_id>",
        question_views.question_modify,
        name="question_modify",
    ),
    # /board/question/delete/305
    path(
        "question/delete/<int:question_id>",
        question_views.question_delete,
        name="question_delete",
    ),
    # 질문 답변 생성
    # /board/answer/create/1
    path(
        "answer/create/<int:question_id>",
        answer_views.answer_create,
        name="answer_create",
    ),
    # /board/answer/modify/1
    path(
        "answer/modify/<int:answer_id>",
        answer_views.answer_modify,
        name="answer_modify",
    ),
    # /board/answer/delete/1
    path(
        "answer/delete/<int:answer_id>",
        answer_views.answer_delete,
        name="answer_delete",
    ),
    # 질문 댓글 생성
    # /board/comment/create/question_id
    path(
        "comment/create/<int:question_id>",
        comment_views.comment_create_question,
        name="comment_create_question",
    ),
    path(
        "comment/modify/<int:comment_id>",
        comment_views.comment_modify_question,
        name="comment_modify_question",
    ),
    path(
        "comment/delete/<int:comment_id>",
        comment_views.comment_delete_question,
        name="comment_delete_question",
    ),
    # 답변 댓글 생성
    path(
        "comment/create_answer/<int:answer_id>",
        comment_views.comment_create_answer,
        name="comment_create_answer",
    ),
    path(
        "comment/modify_answer/<int:comment_id>",
        comment_views.comment_modify_answer,
        name="comment_modify_answer",
    ),
    path(
        "comment/delete_answer/<int:comment_id>",
        comment_views.comment_delete_answer,
        name="comment_delete_answer",
    ),
    path(
        "vote/question/<int:question_id>",
        vote_views.vote_question,
        name="vote_question",
    ),
    path(
        "vote/answer/<int:answer_id>",
        vote_views.vote_answer,
        name="vote_answer",
    ),
]

myapp/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    # http:http://127.0.0.1:8000/ 요청시
    path("", base_views.index, name="index"),
]

myapp/board/models.py
from django.db import models
from django.contrib.auth.models import User

# models.Model 상속받은 것

# 질문 모델( create table Question ~~~)
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    # 작성자 추가
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_question"
    )
    create_date = models.DateTimeField()
    # blank = True : form.is_valid()를 통한 폼 검사시 값이 없어도 됨
    modify_date = models.DateTimeField(null=True, blank=True)
    # 추천수 : 다대다
    voter = models.ManyToManyField(User, related_name="voter_question")

    # 조회수
    view_cnt = models.BigIntegerField(default=0)

    # Question 모델에서 author, voter 필드가 모두 User 모델 참조
    # User.question_set.all or User.question_set.count 같은 명령을 통해 User 모델을 통해서
    # Question 데이터에 접근할 때 author 필드를 기준으로 할지, voter 필드를 기준으로 할지 지정

    def __str__(self) -> str:
        return self.subject + " " + self.content


class QuestionCount(models.Model):
    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip


# 질문에 대한 답변 모델 ( create table Answer ~~~)
class Answer(models.Model):
    # Answer 테이블과 Question 테이블의 외래키 제약조건이 성립
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE
    )  # 질문이 삭제될 시 답변도 같이 삭제되도록 설정
    # 작성자 추가
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_answer"
    )
    content = models.TextField()
    create_date = models.DateTimeField()
    # blank = True : form.is_valid()를 통한 폼 검사시 값이 없어도 됨
    modify_date = models.DateTimeField(null=True, blank=True)
    # 추천수 : 다대다
    voter = models.ManyToManyField(User, related_name="voter_answer")

    def __str__(self) -> str:
        return self.content


# 질문에 대한 댓글 모델
class Comment(models.Model):
    # 댓글 작성자 => user 테이블 정보 사용
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 유저 삭제시 해당 유저가 쓴 댓글 삭제
    # 댓글 내용 => 입력 받기
    content = models.TextField()
    # 댓글 작성날짜
    create_date = models.DateTimeField()
    # 댓글 수정날짜
    modify_date = models.DateTimeField(null=True, blank=True)
    # 질문 정보
    question = models.ForeignKey(
        Question, null=True, blank=True, on_delete=models.CASCADE
    )
    # 답변 정보
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)
    content1 = models.TextField(null=True)

myapp/board/forms.py
from .models import Question, Answer, Comment
from django import forms

# 모델 폼 - 모델과 연결될 폼
# class Meta 반드시 가져야 함


class QuestionForm(forms.ModelForm):  # forms.ModelForm이 자세히 뭘 의미 하는지 모르겠음
    class Meta:
        model = Question
        fields = ["subject", "content"]

        # 에러 메세지가 보여질 때 라벨명이 field명을 이용하기 때문에
        # 영어로 나오는 부분을 원하는 한글로 변경
        labels = {"subject": "제목", "content": "내용"}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]

        # 에러 메세지가 보여질 때 라벨명이 field명을 이용하기 때문에
        # 영어로 나오는 부분을 원하는 한글로 변경
        labels = {"content": "답변 내용"}


# comment 테이블과 연결된 폼 : form.save() -> db반영
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # 사용자 한테 입력 받는거만 fields?
        fields = ["content"]

myapp/board/views/answer_views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from ..models import Question, Answer
from ..forms import AnswerForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# 로그인 확인이 필요할 때
@login_required(login_url="common:login")
def answer_create(request, question_id):
    """
    답변 등록
    """
    # question_id 를 사용해 질문 가져오기
    question = Question.objects.get(id=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            # 작성자 추가(현재 로그인 사용자 : request.user)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            # http://127.0.0.1:8000/board/305#answer_07
            # return redirect("board:detail", question_id=question_id)

            # detail에서 특정 영역 보여주기
            # resolve_url() : 실제 호출되는 URL을 문자열로 반환
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("board:detail", question_id=question_id), answer.id
                )
            )
    else:
        form = AnswerForm()

    context = {"question": question, "form": form}

    return render(request, "board/question_detail.html", context)

    # Answer 객체를 생성한 후 저장 - 모델 폼을 사용하지 않을 때
    # answer = Answer(
    #     question=question,
    #     content=request.POST.get("content"),
    #     create_date=timezone.now(),
    # )
    # answer.save()

    # 답변등록 후 상세 보기 페이지로 이동
    # board/2
    # return redirect("/board/{}".format(question_id), question_id=question_id)


@login_required(login_url="common:login")
def answer_modify(request, answer_id):
    """
    답변 수정 - 원본 내용 찾은 후 수정
    """

    # answer_id 값에 맞는 질문 찾아오기
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, "수정할 권한이 없습니다.")
        return redirect("board:detail", question_id=answer.question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        # 유효성 검증
        if form.is_valid():
            answer = form.save(commit=False)
            # 추가 정보 - 작성자, 수정 날짜
            answer.author = request.user
            answer.modify_date = timezone.now()
            # db 반영
            answer.save()
            # 이동
            # return redirect("board:detail", question_id=answer.question_id)
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("board:detail", question_id=answer.question_id),
                    answer.id,
                )
            )
    else:
        form = AnswerForm(instance=answer)

    return render(request, "board/answer_form.html", {"form": form})


@login_required(login_url="common:login")
def answer_delete(request, answer_id):
    """
    답변 삭제
    """
    # 삭제할 데이터 찾기
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, "삭제할 권한이 없습니다.")
        return redirect("board:detail", question_id=answer.question_id)

    answer.delete()

    return redirect("board:detail", question_id=answer.question_id)

myapp/board/views/base_views.py
from django.shortcuts import get_object_or_404, render
from ..models import Question, QuestionCount
from django.core.paginator import Paginator
from django.db.models import Q, Count
from tools.utils import get_client_ip


def index(request):
    """
    질문목록
    """
    # return HttpResponse("Board")

    # question 테이블 내용 조회
    # Question.objects.all()

    page = request.GET.get("page", 1)  # http://127.0.0.1:8000/board/?page=1
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "")

    # 날짜 최신순으로 목록 조회
    # question_list = Question.objects.order_by("-create_date")

    # annotate() : voter라는 필드의 개수를 센 후 num_vorter라는 임시 필드를 추가해 주는 함수
    if sort == "recent":
        question_list = Question.objects.order_by("-create_date")
    elif sort == "recommend":
        question_list = Question.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-create_date"
        )

    elif sort == "popular":  # 인기순(답변이 많은)
        question_list = Question.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-create_date"
        )
    else:
        question_list = Question.objects.order_by("-create_date")

    # 조회된 목록을 기준으로 검색 조건을 줘서 필터링
    # Q() : OR 조건으로 데이터를 조회
    # subject__contains(대소문자 구별)
    # subject__icontains(대소문자 구별 하지 않음)
    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(author__username__icontains=keyword)
            | Q(answer__author__username__icontains=keyword)
        ).distinct()

    paginator = Paginator(
        question_list, 10
    )  # Paginator 객체 생성(전체목록, 10) 전체목록에서 10개씩 가져오기
    page_obj = paginator.get_page(page)

    context = {
        "question_list": page_obj,
        "page": page,
        "keyword": keyword,
        "sort": sort,
    }

    return render(request, "board/question_list.html", context)


def detail(request, question_id):
    """
    질문 상세 조회
    """
    # 없는 id를 요청했을 때 웹 페이지에 오류 메세지가 그대로 출력
    # question = Question.objects.get(id=question_id)

    # Question에서 id = question_id인 데이터를 가져옴
    question = get_object_or_404(Question, id=question_id)

    # 페이지 나누기 추가
    page = request.GET.get("page", "")  # http://127.0.0.1:8000/board/?page=1
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "")

    # 조회수 추가
    # 사용자 ip 가져오기
    ip = get_client_ip(request)
    # 찾은 ip가 QuestionCount 테이블에 있는지 확인
    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:  # 조회수 증가
        # 모델 생성
        qc = QuestionCount(ip=ip, question=question)
        # 저장
        qc.save()
        # question 테이블에 view_cnt = view_cnt + 1
        if question.view_cnt:
            question.view_cnt += 1
        else:
            question.view_cnt = 1
        question.save()

    context = {"question": question, "keyword": keyword, "sort": sort, "page": page}

    return render(request, "board/question_detail.html", context)

myapp/board/views/comment_views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from ..models import Comment, Question, Answer
from ..forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url="common:login")
def comment_create_question(request, question_id):
    """
    질문 댓글
    """
    # 게시물 번호 가져오기
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            # 추가작업(폼에서 안한 작업)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            # return redirect("board:detail", question_id=question_id)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", question_id=question_id),
                    comment.id,
                ),
            )

    else:
        form = CommentForm()

    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="common:login")
def comment_modify_question(request, comment_id):
    """
    질문 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, "수정할 권한이 없습니다.")
        return redirect("board:detail", question_id=comment.question_id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            # return redirect("board:detail", question_id=comment.question_id)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", question_id=comment.question_id),
                    comment.id,
                ),
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="common:login")
def comment_delete_question(request, comment_id):
    """
    질문 댓글 삭제
    """

    # 삭제할 데이터 찾기
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, "삭제할 권한이 없습니다.")
        return redirect("board:detail", question_id=comment.question_id)

    comment.delete()

    return redirect("board:detail", question_id=comment.question_id)


# ----------------------- answer comment -------------------------------------------------


@login_required(login_url="common:login")
def comment_create_answer(request, answer_id):
    """
    답변 댓글
    """
    # 질문 댓글 번호 가져오기
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            # 추가작업(폼에서 안한 작업)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            # return redirect("board:detail", question_id=answer.question_id)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", question_id=answer.question_id),
                    comment.id,
                ),
            )
    else:
        form = CommentForm()

    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="common:login")
def comment_modify_answer(request, comment_id):
    """
    답변 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, "수정할 권한이 없습니다.")
        return redirect("board:detail", question_id=comment.answer.question_id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            # return redirect("board:detail", question_id=comment.answer.question_id)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", question_id=comment.answer.question_id),
                    comment.id,
                ),
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="common:login")
def comment_delete_answer(request, comment_id):
    """
    답변 댓글 삭제
    """

    # 삭제할 데이터 찾기
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, "삭제할 권한이 없습니다.")
        return redirect("board:detail", question_id=comment.answer.question_id)

    comment.delete()

    return redirect("board:detail", question_id=comment.answer.question_id)

myapp/templates/board/answer_form.html
{% extends 'base.html' %}{% block content %}
<div class="container my-3">
    <form action="" class="post-form my-3" method='post'>
        {% csrf_token %} {% include 'form_errors.html' %}
        <!-- 답변 수정 폼 -->
        <div class="form-group">
            <label for='content'>답변 내용</label>
            <textarea name="content" id="content" rows="10" class='form-control'>{{ form.content.value | default_if_none:'' }}</textarea>
        </div>
        <button type='submit' class='btn btn-primary'>저장하기</button>        
    </form>
</div>
{% endblock %}

myapp/templates/board/comment_form.html
{% extends 'base.html' %}{% block content %}
<div class="container my-3">
    <h5 class="my-3 border-bottom pb-2">댓글 등록</h5>
    <form action="" class="post-form my-3" method='post'>
        {% csrf_token %} {% include 'form_errors.html' %}
        <!-- 댓글 등록 폼 -->
        <div class="form-group">
            <label for='content'>댓글 내용</label>
            <textarea name="content" id="content" rows="10" class='form-control'>{{ form.content.value | default_if_none:'' }}</textarea>
        </div>
        <button type='submit' class='btn btn-primary'>저장하기</button>        
    </form>
</div>
{% endblock %}

myapp/templates/board/question_detail.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container my-3">
  <!--추천 오류 표시-->
  {% if  messages %}
  <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
    <strong> {{message.tags}} </strong>
    <ul>
      <li>{{message.message}} </li>
    </ul>
    {% endfor %}
  </div>
  {% endif %}
  <h2 class="border-bottom py-2">
    <!-- 질문 제목-->
    {{question.subject}}
  </h2>
  <div class="row my-3">
    <!--추천영역-->
    <div class="col-1">
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
        <!--추천 수-->
        {{question.voter.count}}
      </div>
      <a href="#" data-uri=" {% url 'board:vote_question' question.id %}  " class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <!--추천영역 종료-->  
    <div class="col-11">
      <div class="card">
        <div class="card-body">
          <div class="card-text">
            <!--질문 내용-->
            {{question.content |mark}}
          </div>
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">
              <!--작성자-->
              <div class="mb-2">{{question.author.username}}</div>
              <!--질문 작성 날짜-->
              {{question.create_date}}
            </div>
          </div>
          {% if question.modify_date %}
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">          
              <div class="mb-2">modified at</div>
              <!--질문 수정 날짜-->
              {{question.modify_date}}
            </div>
          </div>
          {% endif %}
          {% if question.author == request.user %}
          <div class="my-3">
            <a href=" {% url 'board:question_modify' question.id %}  " class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" data-uri="{% url 'board:question_delete' question.id %}"   class="delete btn btn-sm btn-outline-secondary">삭제</a>
          </div>
          {% endif %}
          <!-- 질문 댓글 영역 start -->
          {% if question.comment_set.count > 0 %}
          <div class="mt-3">            
            {% for comment in question.comment_set.all %}
            <!-- 질문 댓글 앵커 부분-->
            <a name="comment_{{comment.id}}"></a>
            <div class="comment py-2 text-muted">
              <span style="white-space:pre-line">{{comment.content}}</span>
              <span>
                - {{comment.author}}, {{comment.create_date}} 
                {% if comment.modify_date %}
                (수정 : {{comment.modify_date}} )
                {% endif %}
              </span>
              <!--  로그인 사용자 == 작성자 -->
              {% if request.user == comment.author %}
              <a href="{% url 'board:comment_modify_question' comment.id %}" class="small">수정</a>
              <a href="#"  data-uri="{% url 'board:comment_delete_question' comment.id %}" class="delete small">삭제</a>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <div>
            <a href=" {% url 'board:comment_create_question' question.id %} " class="small">댓글 추가...</a>
          </div>
          <!-- 질문 댓글 영역 end -->
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-11">
      <a href="" class="back_to_list btn btn-primary btn-sm my-4"><i class='fas fa-list'> 목록으로</i></a>
    </div>
  </div>
  <h5 class="border-bottom my-3 py-2">
    <!--답변 개수-->
    {{question.answer_set.count}} 개의 답변이 있습니다.
  </h5>  
  {% for answer in question.answer_set.all %}
  <a name="answer_{{answer.id}}"></a>
  <div class="row my-3">
    <!--추천영역-->
    <div class="col-1">
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
        <!--추천 수-->
        {{answer.voter.count}}
      </div>
      <a href="javascript:void(0);" data-uri=" {% url 'board:vote_answer' answer.id %}  " class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <!--추천영역 종료-->  
    <div class="col-11">
      <div class="card">
        <div class="card-body">
          <div class="card-text">
            <!--답변 내용-->
            {{ answer.content |mark }}
          </div>
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">
              <!--작성자-->
              <div class="mb-2">{{answer.author.username}}</div>
              <!--답변 작성 날짜-->
              {{ answer.create_date }}
            </div>
          </div>
          {% if answer.modify_date %}
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">          
              <div class="mb-2">modified at</div>
              <!--답변 수정 날짜-->
              {{answer.modify_date}}
            </div>
          </div>
          {% endif %}
          {% if request.user == answer.author %}
          <div class="my-3">
            <a href=" {% url 'board:answer_modify' answer.id %} " class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" data-uri=" {% url 'board:answer_delete' answer.id %} " class="delete btn btn-sm btn-outline-secondary">삭제</a>
          </div>
          {% endif %}
          <!--답변 댓글 작성부분-->
          <!-- 답변 댓글 영역 start -->
          {% if answer.comment_set.count > 0 %}        
          <div class="mt-3">
            {% for comment in answer.comment_set.all %}
            <!-- 답변 댓글 앵커 부분-->
            <a name="comment_{{comment.id}}"></a>
            <div class="comment py-2 text-muted">
              <span style="white-space:pre-line">{{comment.content}}</span>
              <span>
                - {{comment.author}}, {{comment.create_date}} 
                {% if comment.modify_date %}
                (수정 : {{comment.modify_date}} )
                {% endif %}
              </span>      
              <!--  로그인 사용자 == 작성자 -->
              {% if request.user == comment.author %}  
              <a href="{% url 'board:comment_modify_answer' comment.id %}" class="small">수정</a>
              <a href="#"  data-uri="{% url 'board:comment_delete_answer' comment.id %}" class="delete small">삭제</a>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <div>
            <a href="{% url 'board:comment_create_answer' answer.id %} " class="small">답변 댓글 추가...</a>
          </div>          
        </div>        
      </div>
    </div>
  </div>
  {% endfor %}
  <form
  action=" {% url 'board:answer_create' question.id %} "
  method="post"
  class="my-3"
  >
  {% csrf_token %}
  <!--오류표시-->
  {% if form.errors %}
    <div class="alert alert-danger" role="alert">
    {% for field in form %} {% if field.errors %}
      <strong> {{field.label}} </strong>
      {{field.errors}} {% endif %} {% endfor %}
    </div>
    {% endif %}
    <div class="form-group">
      <textarea
        name="content"
        id="content"
        rows="10"
        class="form-control"
        {% if not user.is_authenticated %}disabled{% endif %}></textarea>
    </div>
    <input type="submit" value="답변 등록" class="btn btn-primary" />
  </form>
</div>
<form action="{% url 'board:index' %}" id='searchForm' method="get">
  <input type="hidden" name="keyword" id='keyword' value="{{keyword|default_if_none:''}}">
  <input type="hidden" name="page" id='page' value="{{page}}">
  <input type="hidden" name="sort" id='sort' value="{{sort}}">
</form>
{% endblock %}
{% block script %}
<script>
$(function(){

  $(".delete").click(function(){
    //console.log($(this).data("uri"))
    if(confirm("정말로 삭제하시겠습니까?")){
      location.href = $(this).data("uri");
    }
  })

  // 추천 버튼 클릭시 data-uri 값 가져오기
  $(".recommend").click(function(){
    //console.log($(this).data("uri"));
    if(confirm("정말로 추천하시겠습니까?")){
      location.href = $(this).data("uri");
    }
  })

  // 목록으로 버튼 클릭시 원래 있던 그곳으로 돌려보내주기
  $('.back_to_list').click(function(){
    $('#searchForm').submit();
  })

})
</script>  
{% endblock  %}
<!--
  request.user : 현재 로그인된 정보(User 객체)

  is_authenticated => 현재 로그인되어 있는 객체를 의미
-->

myapp/templates/board/question_list2.html
<!-- static 폴더 로드 -->
{% load static %}{% comment %} 
<link rel="stylesheet" href="{% static 'css/mystyle.css' %}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<h1>Question List</h1>
<!--
<textarea name="content" id="content" cols="30" rows="10"></textarea> -->

<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>장고수업</td>
                <td>2022-07-22</td>
            </tr>
        </tbody>
    </table>
</div>