myapp/board/urls.py
from django.urls import path
from .views import base_views, answer_views, question_views, comment_views, vote_views

# 네임스페이스 지정
app_name = "board"

urlpatterns = [
    path("", base_views.index, name="index"),
    # 질문 생성
    path("<int:question_id>", base_views.detail, name="detail"),
    # /board/question/create/ question_create
    path("question/create/", question_views.question_create, name="question_create"),
    # /board/question/modify/305
    path(
        "question/modify/<int:question_id>",
        question_views.question_modify,
        name="question_modify",
    ),
    # /board/question/delete/305
    path(
        "question/delete/<int:question_id>",
        question_views.question_delete,
        name="question_delete",
    ),
    # 질문 답변 생성
    # /board/answer/create/1
    path(
        "answer/create/<int:question_id>",
        answer_views.answer_create,
        name="answer_create",
    ),
    # /board/answer/modify/1
    path(
        "answer/modify/<int:answer_id>",
        answer_views.answer_modify,
        name="answer_modify",
    ),
    # /board/answer/delete/1
    path(
        "answer/delete/<int:answer_id>",
        answer_views.answer_delete,
        name="answer_delete",
    ),
    # 질문 댓글 생성
    # /board/comment/create/question_id
    path(
        "comment/create/<int:question_id>",
        comment_views.comment_create_question,
        name="comment_create_question",
    ),
    path(
        "comment/modify/<int:comment_id>",
        comment_views.comment_modify_question,
        name="comment_modify_question",
    ),
    path(
        "comment/delete/<int:comment_id>",
        comment_views.comment_delete_question,
        name="comment_delete_question",
    ),
    # 답변 댓글 생성
    path(
        "comment/create_answer/<int:answer_id>",
        comment_views.comment_create_answer,
        name="comment_create_answer",
    ),
    path(
        "comment/modify_answer/<int:comment_id>",
        comment_views.comment_modify_answer,
        name="comment_modify_answer",
    ),
    path(
        "comment/delete_answer/<int:comment_id>",
        comment_views.comment_delete_answer,
        name="comment_delete_answer",
    ),
    path(
        "vote/question/<int:question_id>",
        vote_views.vote_question,
        name="vote_question",
    ),
    path(
        "vote/answer/<int:answer_id>",
        vote_views.vote_answer,
        name="vote_answer",
    ),
]

myapp/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# 네임스페이스 지정
app_name = "common"

urlpatterns = [
    # django.contrib.auth 에서 제공하는 LoginView 클래스를 활용하기 때문에 별도의 views 는 작성하지 않음
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "signup/",
        views.signup,
        name="signup",
    ),
]

myapp/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    # http:http://127.0.0.1:8000/ 요청시
    path("", base_views.index, name="index"),
]

myapp/common/models.py
from django.db import models

# Create your models here.

myapp/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

myapp/common/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from .forms import UserForm

# Create your views here.
def signup(request):
    """
    회원가입
    """
    if request.method == "POST":
        # 사용자가 입력한 폼 가져오기
        form = UserForm(request.POST)
        if form.is_valid():
            # db 반영
            form.save()
            # 로그인 페이지를 보여줄 때
            # return redirect("common:login")

            # form.cleaned_data.get() : 넘어온 폼에서 화면의 입력 값을 얻기 위한 함수
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")

            # authenticate() : 사용자아이디와 비밀번호를 담아서 자격증명을 요청하는 함수
            user = authenticate(username=username, password=raw_password)

            if user is not None:
                # login() : 로그인 해주는 함수
                login(request, user)
            return redirect("index")
    else:
        form = UserForm()

    return render(request, "common/signup.html", {"form": form})

myapp/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 회원가입 메뉴 -->
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                또는 <a href=" {% url 'common:signup' %} ">계정을 만드세요</a>
            </span>
        </div>
    </div>
    <!-- 회원가입 메뉴 종료 -->
    <form action="" method='post' class='post-form'>
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for='username'>사용자 ID</label>
            <input type="text" name="username" id="username" class='form-control' value='{{form.username.value|default_if_none:''}}'>
        </div>
        <div class="form-group">
            <label for='password'>비밀번호</label>
            <input type="password" name="password" id="password" class='form-control' value='{{form.password.value|default_if_none:''}}'>
        </div>
        <div>
            <button type="submit" class='btn btn-primary'>로그인</button>
        </div>
    </form>
</div>
{% endblock %}

myapp/templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요</a></span>
        </div>
    </div>
    <form method='post' class='post-form'>
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for='username'>사용자 ID</label>
            <input type="text" name="username" id="username" class='form-control' value='{{form.username.value|default_if_none:''}}'>
        </div>
        <div class="form-group">
            <label for='password1'>비밀번호</label>
            <input type="password" name="password1" id="password1" class='form-control' value='{{form.password1.value|default_if_none:''}}'>
        </div>
        <div class="form-group">
            <label for='password2'>비밀번호</label>
            <input type="password" name="password2" id="password2" class='form-control' value='{{form.password2.value|default_if_none:''}}'>
        </div>
        <div class="form-group">
            <label for='email'>이메일</label>
            <input type="text" name="email" id="email" class='form-control' value='{{form.email.value|default_if_none:''}}'>
        </div>
        <div>
            <button type="submit" class='btn btn-primary'>회원가입</button>
        </div>
    </form>
</div>





{% endblock  %}