myapp/board/urls.py
from django.urls import path
from .views import base_views, answer_views, question_views, comment_views, vote_views

# 네임스페이스 지정
app_name = "board"

urlpatterns = [
    path("", base_views.index, name="index"),
    # 질문 생성
    path("<int:question_id>", base_views.detail, name="detail"),
    # /board/question/create/ question_create
    path("question/create/", question_views.question_create, name="question_create"),
    # /board/question/modify/305
    path(
        "question/modify/<int:question_id>",
        question_views.question_modify,
        name="question_modify",
    ),
    # /board/question/delete/305
    path(
        "question/delete/<int:question_id>",
        question_views.question_delete,
        name="question_delete",
    ),
    # 질문 답변 생성
    # /board/answer/create/1
    path(
        "answer/create/<int:question_id>",
        answer_views.answer_create,
        name="answer_create",
    ),
    # /board/answer/modify/1
    path(
        "answer/modify/<int:answer_id>",
        answer_views.answer_modify,
        name="answer_modify",
    ),
    # /board/answer/delete/1
    path(
        "answer/delete/<int:answer_id>",
        answer_views.answer_delete,
        name="answer_delete",
    ),
    # 질문 댓글 생성
    # /board/comment/create/question_id
    path(
        "comment/create/<int:question_id>",
        comment_views.comment_create_question,
        name="comment_create_question",
    ),
    path(
        "comment/modify/<int:comment_id>",
        comment_views.comment_modify_question,
        name="comment_modify_question",
    ),
    path(
        "comment/delete/<int:comment_id>",
        comment_views.comment_delete_question,
        name="comment_delete_question",
    ),
    # 답변 댓글 생성
    path(
        "comment/create_answer/<int:answer_id>",
        comment_views.comment_create_answer,
        name="comment_create_answer",
    ),
    path(
        "comment/modify_answer/<int:comment_id>",
        comment_views.comment_modify_answer,
        name="comment_modify_answer",
    ),
    path(
        "comment/delete_answer/<int:comment_id>",
        comment_views.comment_delete_answer,
        name="comment_delete_answer",
    ),
    path(
        "vote/question/<int:question_id>",
        vote_views.vote_question,
        name="vote_question",
    ),
    path(
        "vote/answer/<int:answer_id>",
        vote_views.vote_answer,
        name="vote_answer",
    ),
]

myapp/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# 네임스페이스 지정
app_name = "common"

urlpatterns = [
    # django.contrib.auth 에서 제공하는 LoginView 클래스를 활용하기 때문에 별도의 views 는 작성하지 않음
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "signup/",
        views.signup,
        name="signup",
    ),
]

myapp/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    # http:http://127.0.0.1:8000/ 요청시
    path("", base_views.index, name="index"),
]

myapp/board/views/base_views.py
from django.shortcuts import get_object_or_404, render
from ..models import Question, QuestionCount
from django.core.paginator import Paginator
from django.db.models import Q, Count
from tools.utils import get_client_ip


def index(request):
    """
    질문목록
    """
    # return HttpResponse("Board")

    # question 테이블 내용 조회
    # Question.objects.all()

    page = request.GET.get("page", 1)  # http://127.0.0.1:8000/board/?page=1
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "")

    # 날짜 최신순으로 목록 조회
    # question_list = Question.objects.order_by("-create_date")

    # annotate() : voter라는 필드의 개수를 센 후 num_vorter라는 임시 필드를 추가해 주는 함수
    if sort == "recent":
        question_list = Question.objects.order_by("-create_date")
    elif sort == "recommend":
        question_list = Question.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-create_date"
        )

    elif sort == "popular":  # 인기순(답변이 많은)
        question_list = Question.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-create_date"
        )
    else:
        question_list = Question.objects.order_by("-create_date")

    # 조회된 목록을 기준으로 검색 조건을 줘서 필터링
    # Q() : OR 조건으로 데이터를 조회
    # subject__contains(대소문자 구별)
    # subject__icontains(대소문자 구별 하지 않음)
    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(author__username__icontains=keyword)
            | Q(answer__author__username__icontains=keyword)
        ).distinct()

    paginator = Paginator(
        question_list, 10
    )  # Paginator 객체 생성(전체목록, 10) 전체목록에서 10개씩 가져오기
    page_obj = paginator.get_page(page)

    context = {
        "question_list": page_obj,
        "page": page,
        "keyword": keyword,
        "sort": sort,
    }

    return render(request, "board/question_list.html", context)


def detail(request, question_id):
    """
    질문 상세 조회
    """
    # 없는 id를 요청했을 때 웹 페이지에 오류 메세지가 그대로 출력
    # question = Question.objects.get(id=question_id)

    # Question에서 id = question_id인 데이터를 가져옴
    question = get_object_or_404(Question, id=question_id)

    # 페이지 나누기 추가
    page = request.GET.get("page", "")  # http://127.0.0.1:8000/board/?page=1
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "")

    # 조회수 추가
    # 사용자 ip 가져오기
    ip = get_client_ip(request)
    # 찾은 ip가 QuestionCount 테이블에 있는지 확인
    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:  # 조회수 증가
        # 모델 생성
        qc = QuestionCount(ip=ip, question=question)
        # 저장
        qc.save()
        # question 테이블에 view_cnt = view_cnt + 1
        if question.view_cnt:
            question.view_cnt += 1
        else:
            question.view_cnt = 1
        question.save()

    context = {"question": question, "keyword": keyword, "sort": sort, "page": page}

    return render(request, "board/question_detail.html", context)

myapp/templates/base.html
<!-- header, footer 역할 -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href=" {% static 'css/mystyle.css' %} ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <title>장고 게시판</title>
</head>
<body>
    {% include 'navbar.html' %}
    <!-- 기본 템플릿 안에 삽입 시작 -->
    {% block content %}
    <!-- 각 페이지마다 다른 내용 작성 -->
    {% endblock %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block script %}
    {% endblock  %}
</body>
</html>

myapp/templates/form_errors.html
<!-- 오류표시 -->
{% if form.errors %}
    {% for field in form %}
    <!-- form 안의 요소들 오류 출력 : 입력값 누락, 형식에 맞지 않는 경우 -->
        {% for error in field.errors %}
            <div class="alert alert-danger" role='alert'>
                <strong>{{field.label}}</strong>
                {{error}}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in field.non_field_errors %}
    <!-- non_field_errors : 입력값과 관계없이 발생한 오류 -->
        <div class="alert alert-danger" role='alert'>
            <strong>{{error}}</strong>
        </div>
    {% endfor %}
{% endif %}

myapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <a class="navbar-brand" href="{% url 'board:index' %}">Board</a>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">  
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'common:logout' %}"> {{user.username}} 로그아웃</a>
        {% else %}
          <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>